feat: Update unit tests for maple-token (SC-3157)
maple-labs/maple-token pull request #13
Opened 2021-08-09 13:55 UTC by satyamakgec

2021-08-09 15:11 UTC, lucas-manuel requested changes
Great PR, small changes

2021-08-09 15:11 UTC, lucas-manuel commented on contracts/test/MapleToken.t.sol
> +    uint256 holder2Pk = 2;
We should use `owner` and `spender` to make things more clear

2021-08-09 15:11 UTC, lucas-manuel commented on contracts/test/MapleToken.t.sol
> +    uint256 deadline  = 5000000000; // timestamp far in the future
Two spaces between ; and // and capital first letter:
`uint256 deadline = 5000000000;  // Timestamp far in the future`

2021-08-09 15:11 UTC, lucas-manuel commented on contracts/test/MapleToken.t.sol
> +    address spender = holder2; // address of user who `owner` is approving
Same comment format as above

2021-08-09 15:11 UTC, lucas-manuel commented on contracts/test/MapleToken.t.sol
> +        (uint8 v, bytes32 r, bytes32 s)= getValidPermitSignature(amount, holder1, holder1Pk, deadline);
`bytes32 s) = `

2021-08-09 15:11 UTC, lucas-manuel commented on contracts/test/MapleToken.t.sol
> +    uint256 holder2Pk = 2;
Should also use `sk` instead of `pk` `pk` can be confused for public key

2021-08-09 15:11 UTC, lucas-manuel commented on contracts/test/MapleToken.t.sol
> +        (uint8 v, bytes32 r, bytes32 s)= getValidPermitSignature(amount, holder1, holder1Pk, deadline);
`bytes32 s) =`

2021-08-09 15:11 UTC, lucas-manuel commented on contracts/test/MapleToken.t.sol
> +        (uint8 v, bytes32 r, bytes32 s)= getValidPermitSignature(amount, holder1, holder1Pk, deadline);
`bytes32 s) = `

2021-08-09 15:11 UTC, lucas-manuel commented on contracts/test/MapleToken.t.sol
> +        (v, r, s)= getValidPermitSignature(amount, holder2, holder2Pk, deadline);
`) =`

2021-08-09 15:11 UTC, lucas-manuel commented on contracts/test/MapleToken.t.sol
> +        (v, r, s)= getValidPermitSignature(amount, holder1, holder1Pk, expiry);
`) =`

2021-08-09 15:11 UTC, lucas-manuel commented on contracts/test/MapleToken.t.sol
> +        assertTrue(!usr.try_permit(holder1, holder2, amount, uint(-1), v, r, s));
I think we should use `deadline` twice here

2021-08-10 22:49 UTC, lucas-manuel commented on contracts/test/MapleToken.t.sol
> +        bytes32 digest = getDigest(owner_, spender, value, nonce, deadline_);
`ownersk`

2021-08-11 01:10 UTC, deluca-mike requested changes
Tests should be in `test_camelCase`.

2021-08-11 01:24 UTC, deluca-mike submitted a review, later dismissed

2021-08-11 03:05 UTC, lucas-manuel approved these changes

2021-08-11 03:05 UTC, merged